services:
  homerag-webui:
    container_name: homerag-webui
    image: mchelenakinyesi/homerag-webui:latest
    environment:
      - LLM_HOST=
      - MODEL_NAME=
      - LLM_TOKEN=
    ports:
      - "1024:1024"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
